[package]
name = "decoding"
version = "0.1.0"
authors = ["Alexander Popiak <alexander.popiak@parity.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# parity-scale-codec = "1.3.1"
hex = "0.4.2"
sp-io = "2.0.0"
